_wandb:
    value:
        cli_version: 0.25.1
        e:
            thca6uoov5sz2l5nh39ankkfdli9ppc7:
                codePath: learn_rl.py
                codePathLocal: learn_rl.py
                cpu_count: 6
                cpu_count_logical: 6
                cudaVersion: "13.1"
                disk:
                    /:
                        total: "1081101176832"
                        used: "57290313728"
                email: xz573@cam.ac.uk
                executable: /home/xyzha/miniconda3/envs/vsdrl_env_5060/bin/python
                git:
                    commit: fe4a2bf9e61266bf7bd436a3a60f1cb0964f3fc1
                    remote: https://github.com/ZoeCE/Flexible_DDPGwB.git
                gpu: NVIDIA GeForce RTX 5060 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Blackwell
                      memoryTotal: "8546942976"
                      name: NVIDIA GeForce RTX 5060 Laptop GPU
                      uuid: GPU-3a45bc42-4891-2a53-288a-5b94f8fce51e
                host: Xiaoyu
                memory:
                    total: "12543823872"
                os: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.39
                program: /mnt/d/ResearchProject/DDPG/Flexible_DDPGwB/learn_rl.py
                python: CPython 3.11.14
                root: saves/pure_rl_experiment
                startedAt: "2026-03-26T14:01:00.966752Z"
                writerId: thca6uoov5sz2l5nh39ankkfdli9ppc7
        m: []
        python_version: 3.11.14
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
                - 16
                - 61
            "4": 3.11.14
            "5": 0.25.1
            "12": 0.25.1
            "13": linux-x86_64
action_dim:
    value: 3
base_boot:
    value: false
batch_size:
    value: 64
behavior_clone:
    value: false
explore_noise_end:
    value: 0.02
explore_noise_start:
    value: 0.1
gamma:
    value: 0.94
max_action:
    value: 0.5
max_steps_per_ep:
    value: 150
mode:
    value: pure_rl
n_episodes:
    value: 4000
policy_freq:
    value: 2
policy_noise:
    value: 0.1
state_dim:
    value: 23
tau:
    value: 0.005
warmup_steps:
    value: 10000
